<a href="https://colab.research.google.com/github/SamTremblay18/Hockey-Shot-Classification/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import random
from google.colab import drive
drive.mount('/content/drive')
import pickle
from sklearn.preprocessing import LabelEncoder, MaxAbsScaler, StandardScaler
import matplotlib.pyplot as plt
from scipy import signal
from sklearn.model_selection import train_test_split
from itertools import chain

Mounted at /content/drive

# Functions

Save and open files with pickle

In [ ]:
def save_pickle(path_pickle,P):
  f = open(path_pickle, 'wb')
  pickle.dump(P, f)
  f.close()

  return f

def open_pickle(path_pickle):
  f = open(path_pickle, 'rb')
  P = pickle.load(f)
  f.close()

  return P

Regroups all the Pre, SH and Post trials together to the label 'Other'

In [ ]:
def regroup_other(P_markers,P_acc):
  for i in range(0,len(P_markers.iloc[:,0])):

    length_trial = P_markers.iloc[i,2]
    start_trial = P_markers.iloc[i,0]

    if P_markers.iloc[i,1] == 'Pre' or P_markers.iloc[i,1] == 'SH' or P_markers.iloc[i,1] == 'post':
      P_acc.loc[(start_trial):(start_trial)+((length_trial)-1),'Label'] = 'Other' # Swapping the label to Other

  return P_acc

Reframe all the shooting trials the same frame length

In [ ]:
def reframe(P_markers,P_acc,f_length):
  for i in range(0,len(P_markers.iloc[:,0])):

    length_trial = P_markers.iloc[i,2]
    start_trial = P_markers.iloc[i,0]
    type_shot = P_markers.iloc[i,1]

    if P_markers.iloc[i,1] == 'BH' or P_markers.iloc[i,1] == 'Pass' or P_markers.iloc[i,1] == 'SS' or P_markers.iloc[i,1] == 'WS' or P_markers.iloc[i,1] == 'OT':
        diff = int(f_length-length_trial) # Identifying how many frames are missing to have the desired length
        P_acc.iloc[int(start_trial)-diff:int(start_trial)+int(length_trial),-1] = type_shot # Swapping the old labels from the difference
                                                                                            # found above to the new label desired
  return P_acc

Standardize and label encoder function

In [ ]:
def stand_labelencoder(P_acc):
  # scaler = StandardScaler()
  le = LabelEncoder()
  trimmed = P_acc.iloc[:,1:-1]
  # scaled = scaler.fit_transform(P_acc.iloc[:,1:-1], y = P_acc['Label'])
  y = le.fit_transform(P_acc['Label'])
  classes = le.classes_
  y = y[:,None]
  x = np.concatenate((trimmed, y), axis=1)

  return x, classes

In [ ]:
def x_scaler(X_train, X_valid, X_test=None):

  # Fit scaler using train manually
  mean = X_train.mean(axis=(0, 1), keepdims=True)   # shape (1,1,channels)
  std = X_train.std(axis=(0, 1), keepdims=True)

  # transform
  X_train = (X_train - mean) / std
  X_valid = (X_valid - mean) / std

  if X_test is not None:
    X_test = (X_test - mean) / std

  return X_train, X_valid, X_test

Create tensors of specific shape

In [ ]:
def create_tensor(P_acc,f_length):
  trials_length = len(P_acc)/f_length
  T = np.stack(np.split(P_acc, trials_length), axis=1)
  Tensors = tf.constant(T.astype('float32'))
  Tensors = tf.transpose(Tensors, perm = [1, 0, 2])

  return Tensors

Create 15 trials of 'Other' with specific length

In [ ]:
# The majority of the data is in the category 'Other', so this function randomly creates
# 15 trials from data labeled as 'Other' with the specified length
def other_class(P_other,f_length):
  random.seed(4)
  num_list = random.sample(range(0,len(P_other),f_length),15) # this creates 15 numbers that are seperated with at least
                                                              # the specified length from all the data labeled as 'Other'
  Other_all = pd.DataFrame()
  for i in num_list:
    other = P_other.iloc[i:(i+f_length),:] # creates the trials with the specified length starting with number from the list
    Other_all = pd.concat([Other_all, other], ignore_index = True)

  return Other_all

Runs all the preprocessing steps for the reframe method

In [ ]:
def Preprocess(P_markers, P_acc):
  P_data = regroup_other(P_markers,P_acc) # regroups the 'SH', 'Pre', 'post' trials to the label 'Other'
  P_data = reframe(P_markers,P_data,576) # reframe the dataset to 576 frames
  P_other = P_data[(P_data['Label'] == 'Other')] # creates a variable containing all the data labeled 'Other'
  P_other_all = other_class(P_other,576) # from the variable above, creates 15 trials of length 576
  P_data = P_data.drop(P_data[(P_data['Label'] == 'Do not use')].index) # removing all the data labeled as 'Do not use' (junk)
  P_data = P_data.drop(P_data[(P_data['Label'] == 'Other')].index) # removing all the data labeled as 'Other' from the original dataset
  P_data = pd.concat([P_data, P_other_all], ignore_index = True) # adding the 15 'Other' trials of length 576 to the original dataset
  P_data, classes = stand_labelencoder(P_data)  # in this function, P_data is only trimmed not scaled. y is encoded
  P_data = create_tensor(P_data,576) # transforming the dataset into tensors with a length of 576 frames

  return P_data, classes

Resample the shot trials to a set frequency

In [ ]:
def resampling_data(markers_number, p_resample, p_acc, sampling_freq):

  for i in range(0,len(markers[markers_number].iloc[:-1,2])):

          trial_start = markers[markers_number].iloc[i,0]
          typeshot = markers[markers_number].iloc[i,1]
          trial_len = markers[markers_number].iloc[i,2]

          if typeshot == 'WS':
            # Resamples a trial by selecting all the data except the 'Frame' and 'label' column to a specified frequency
            data_resample[p_resample][f'WS_{i}'] = signal.resample(data_biomech_config[p_acc].iloc[int(trial_start):(int(trial_start)+int(trial_len)),1:-1],sampling_freq)
            # Adds the labels encoded manually at the last column position
            data_resample[p_resample][f'WS_{i}'] = np.append(data_resample[p_resample][f'WS_{i}'], np.full((sampling_freq,1), 6), axis=1)

          elif typeshot == 'BH':
            data_resample[p_resample][f'BH_{i}'] = signal.resample(data_biomech_config[p_acc].iloc[int(trial_start):(int(trial_start)+int(trial_len)),1:-1],sampling_freq)
            data_resample[p_resample][f'BH_{i}'] = np.append(data_resample[p_resample][f'BH_{i}'], np.full((sampling_freq,1), 0), axis=1)

          elif typeshot == 'OT':
            data_resample[p_resample][f'OT_{i}'] = signal.resample(data_biomech_config[p_acc].iloc[int(trial_start):(int(trial_start)+int(trial_len)),1:-1],sampling_freq)
            data_resample[p_resample][f'OT_{i}'] = np.append(data_resample[p_resample][f'OT_{i}'], np.full((sampling_freq,1), 1), axis=1)

          elif typeshot == 'SS':
            data_resample[p_resample][f'SS_{i}'] = signal.resample(data_biomech_config[p_acc].iloc[int(trial_start):(int(trial_start)+int(trial_len)),1:-1],sampling_freq)
            data_resample[p_resample][f'SS_{i}'] = np.append(data_resample[p_resample][f'SS_{i}'], np.full((sampling_freq,1), 5), axis=1)

          elif typeshot == 'Pass':
            data_resample[p_resample][f'Pass_{i}'] = signal.resample(data_biomech_config[p_acc].iloc[int(trial_start):(int(trial_start)+int(trial_len)),1:-1],sampling_freq)
            data_resample[p_resample][f'Pass_{i}'] = np.append(data_resample[p_resample][f'Pass_{i}'], np.full((sampling_freq,1), 3), axis=1)

          else:
            continue

#Method 1 - Reframe to 576 frames and All Sensors Configuration

In [ ]:
# Participants' and markers' dictionnary
data = open_pickle('/content/drive/MyDrive/Sam/File_saved/P_dct.pickle')
markers = open_pickle('/content/drive/MyDrive/Sam/File_saved/markers_dct.pickle')

In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict

# --- Initialize ---
tasks_of_interest = ["WS", "SS", "OT", "BH", "Pass"]
frame_counts = defaultdict(list)

# --- Loop through all participant DataFrames ---
for pid, df in data.items():
    if not isinstance(df, pd.DataFrame):
        continue  # skip non-DataFrames if any

    if "Label" not in df.columns:
        print(f"Warning: no 'Label' column found for {pid}")
        continue

    # Count contiguous frames belonging to each label
    current_label = None
    count = 0
    for label in df["Label"]:
        if label == current_label:
            count += 1
        else:
            # store previous segment length
            if current_label in tasks_of_interest:
                frame_counts[current_label].append(count)
            # reset counter
            current_label = label
            count = 1
    # store final segment
    if current_label in tasks_of_interest:
        frame_counts[current_label].append(count)

# --- Summarize ---
summary = []
for task in tasks_of_interest:
    if len(frame_counts[task]) > 0:
        counts = np.array(frame_counts[task])
        summary.append({
            "Task": task,
            "Num Segments": len(counts),
            "Min Frames": counts.min(),
            "Mean Frames": counts.mean()
        })
    else:
        summary.append({
            "Task": task,
            "Num Segments": 0,
            "Min Frames": np.nan,
            "Mean Frames": np.nan
        })

summary_df = pd.DataFrame(summary)
print(summary_df)

# Optional: save for reference
# summary_df.to_csv("frame_length_summary.csv", index=False)

   Task  Num Segments  Min Frames  Mean Frames
0    WS           588         152   329.899660
1    SS           584         272   427.486301
2    OT           393         264   392.748092
3    BH           389         192   330.290488
4  Pass           195         152   268.830769

In [ ]:
print(data['P01_acc'].shape)
print(markers['P01_markers'].shape)
data['P01_acc'].head()

(398056, 53)
(169, 3)

,Frame,Pelvis x,Pelvis y,Pelvis z,T8 x,T8 y,T8 z,Head x,Head y,Head z,...,Left Upper Leg x,Left Upper Leg y,Left Upper Leg z,Left Lower Leg x,Left Lower Leg y,Left Lower Leg z,Left Foot x,Left Foot y,Left Foot z,Label
0,0,-0.000099,0.000712,-0.001159,0.246312,0.497346,-0.011794,0.345373,0.292784,0.172301,...,0.197891,-0.037716,-0.172511,0.441520,0.708759,-0.073357,0.267160,0.507843,-0.020744,Do not use
1,1,0.085870,-0.087079,-0.057492,0.270516,0.329011,-0.041490,0.342595,0.234431,-0.069587,...,0.286065,-0.283458,-0.174133,0.460206,0.508014,-0.051261,0.277574,0.392253,-0.037118,Do not use
2,2,0.043551,0.023407,0.000055,0.144880,0.406876,-0.017420,0.333028,0.329907,0.038479,...,0.222336,-0.221622,-0.120159,0.261654,0.588018,0.066416,0.195962,0.589012,0.046372,Do not use
3,3,-0.052281,0.032851,0.023840,0.005390,0.444358,0.020782,0.121774,0.415970,-0.086135,...,0.159082,-0.272581,-0.061035,0.051586,0.487235,0.108227,-0.042877,0.572785,0.003310,Do not use
4,4,0.005050,0.062071,0.025009,0.033177,0.315881,-0.070002,0.261215,0.304412,-0.195614,...,0.200309,-0.383079,-0.046320,-0.065462,0.314675,0.132233,0.055484,0.435952,-0.003216,Do not use

In [ ]:
# Preprocess function for method 1 and storing into P_processed1 dictionary
P_processed1 = {}
for l,n in zip(markers, data):
  P_processed1[f'{n}_processed'], data_classes1 = Preprocess(markers[l],data[n])

In [ ]:
data_classes1

array(['BH', 'OT', 'Other', 'Pass', 'Rest', 'SS', 'WS'], dtype=object)

In [ ]:
# Subject-wise shuffling
keys = list(P_processed1.keys())
random.seed(10)
random.shuffle(keys)
ShuffledP_processed1_1 = dict()
for key in keys:
    ShuffledP_processed1_1.update({key: P_processed1[key]})

In [ ]:
# fold 1
train_values1 = list(ShuffledP_processed1_1.values())[0:31]
x_train_all1 = tf.concat(train_values1[0:31], axis = 0)
X_train_all1 = x_train_all1[:,:,:-1].numpy()
y_train_all1 = x_train_all1[:,0,-1].numpy()
random.seed(6)
random.shuffle(train_values1)

x_train1_1 = tf.concat(train_values1[0:27], axis = 0)
X_train1_1 = x_train1_1[:,:,:-1].numpy()
y_train1_1 = x_train1_1[:,0,-1].numpy()

x_valid1_1 = tf.concat(train_values1[27:31], axis = 0)
X_valid1_1 = x_valid1_1[:,:,:-1].numpy()
y_valid1_1 = x_valid1_1[:,0,-1].numpy()

test_values1 = list(ShuffledP_processed1_1.values())[31:39]
x_test1 = tf.concat(test_values1, axis = 0)
X_test1 = x_test1[:,:,:-1].numpy()
y_test1 = x_test1[:,0,-1].numpy()

# scale
X_train1_1, X_valid1_1, _  = x_scaler(X_train1_1, X_valid1_1)


print("X_train:",X_train1_1.shape,
      "X_test:",X_test1.shape,
      "X_valid:",X_valid1_1.shape,
      "y_train:",y_train1_1.shape,
      "y_test:",y_test1.shape,
      "y_valid:",y_valid1_1.shape,
      "X_train:",X_train_all1.shape,
      "y_train:",y_train_all1.shape)

X_train: (2298, 576, 51) X_test: (681, 576, 51) X_valid: (340, 576, 51) y_train: (2298,) y_test: (681,) y_valid: (340,) X_train: (2638, 576, 51) y_train: (2638,)

In [ ]:

save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train1_1.pickle',X_train1_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid1_1.pickle',X_valid1_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_test1.pickle',y_test1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train1_1.pickle',y_train1_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid1_1.pickle',y_valid1_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train_all1.pickle',y_train_all1)

In [ ]:
# ---- Global scaler for the FINAL model (fit on TRAIN_ALL only) ----
import numpy as np

def x_scaler(X_train, X_valid=None, X_test=None, mean=None, std=None, return_params=False, eps=1e-8):
    if mean is None or std is None:
        mean = X_train.mean(axis=(0, 1), keepdims=True)
        std  = X_train.std(axis=(0, 1), keepdims=True)
    std = np.where(std < eps, eps, std)

    X_train = (X_train - mean) / std
    X_valid = None if X_valid is None else (X_valid - mean) / std
    X_test  = None if X_test  is None else (X_test  - mean) / std

    if return_params:
        return X_train, X_valid, X_test, {"mean": mean, "std": std}
    return X_train, X_valid, X_test

# Fit on TRAIN_ALL; apply to TRAIN_ALL (for your final model) and to TEST
X_train_all1_sc, _, X_test1_sc, scale_global = x_scaler(
    X_train_all1, None, X_test1, return_params=True
)

# Save the scaled arrays (or at least the scale params)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train_all1_sc.pickle', X_train_all1_sc)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_test1_sc.pickle',     X_test1_sc)
save_pickle('/content/drive/MyDrive/Sam/File_saved/scale_global.pickle',   scale_global)

# Quick sanity check (optional)
def stats(X, name):
    mu = X.mean(axis=(0,1)); sd = X.std(axis=(0,1))
    print(f"{name}: mean[:5]={mu[:5]}, std[:5]={sd[:5]}")

stats(X_train_all1_sc, "TRAIN_ALL1_sc")
stats(X_test1_sc,     "TEST_sc")
# stds should be ≈1 and means ≈0 per channel for both.

TRAIN_ALL1_sc: mean[:5]=[ 8.8758201e-09 -1.3062748e-08 -4.7643272e-08 -4.0419813e-08
  5.3273745e-08], std[:5]=[0.99997646 0.99990726 0.9999726  0.9999526  0.9999804 ]
TEST_sc: mean[:5]=[-7.8398400e-05 -1.6366413e-03 -4.8996112e-04  9.3836436e-04
 -5.8647166e-03], std[:5]=[0.85469323 0.8941036  0.916937   0.8783274  0.9018153 ]

In [ ]:
# fold 2
random.seed(7)
random.shuffle(train_values1)

x_train1_2 = tf.concat(train_values1[0:27], axis = 0)
X_train1_2 = x_train1_2[:,:,:-1].numpy()
y_train1_2 = x_train1_2[:,0,-1].numpy()

x_valid1_2 = tf.concat(train_values1[27:31], axis = 0)
X_valid1_2 = x_valid1_2[:,:,:-1].numpy()
y_valid1_2 = x_valid1_2[:,0,-1].numpy()

# scale
X_train1_2, X_valid1_2, _ = x_scaler(X_train1_2, X_valid1_2)


print("X_train:",X_train1_2.shape,
      "X_valid:",X_valid1_2.shape,
      "y_train:",y_train1_2.shape,
      "y_valid:",y_valid1_2.shape)

X_train: (2298, 576, 51) X_valid: (340, 576, 51) y_train: (2298,) y_valid: (340,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train1_2.pickle',X_train1_2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train1_2.pickle',y_train1_2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid1_2.pickle',X_valid1_2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid1_2.pickle',y_valid1_2)

In [ ]:
# fold 3
random.seed(8)
random.shuffle(train_values1)

x_train1_3 = tf.concat(train_values1[0:27], axis = 0)
X_train1_3 = x_train1_3[:,:,:-1].numpy()
y_train1_3 = x_train1_3[:,0,-1].numpy()

x_valid1_3 = tf.concat(train_values1[27:31], axis = 0)
X_valid1_3 = x_valid1_3[:,:,:-1].numpy()
y_valid1_3 = x_valid1_3[:,0,-1].numpy()

# scale
X_train1_3, X_valid1_3, _ = x_scaler(X_train1_3, X_valid1_3)


print("X_train:",X_train1_3.shape,
      "X_valid:",X_valid1_3.shape,
      "y_train:",y_train1_3.shape,
      "y_valid:",y_valid1_3.shape)

X_train: (2298, 576, 51) X_valid: (340, 576, 51) y_train: (2298,) y_valid: (340,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train1_3.pickle',X_train1_3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train1_3.pickle',y_train1_3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid1_3.pickle',X_valid1_3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid1_3.pickle',y_valid1_3)

In [ ]:
# fold 4
random.seed(9)
random.shuffle(train_values1)

x_train1_4 = tf.concat(train_values1[0:27], axis = 0)
X_train1_4 = x_train1_4[:,:,:-1].numpy()
y_train1_4 = x_train1_4[:,0,-1].numpy()

x_valid1_4 = tf.concat(train_values1[27:31], axis = 0)
X_valid1_4 = x_valid1_4[:,:,:-1].numpy()
y_valid1_4 = x_valid1_4[:,0,-1].numpy()

# scale
X_train1_4, X_valid1_4, _ = x_scaler(X_train1_4, X_valid1_4)


print("X_train:",X_train1_4.shape,
      "X_valid:",X_valid1_4.shape,
      "y_train:",y_train1_4.shape,
      "y_valid:",y_valid1_4.shape)

X_train: (2297, 576, 51) X_valid: (341, 576, 51) y_train: (2297,) y_valid: (341,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train1_4.pickle',X_train1_4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train1_4.pickle',y_train1_4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid1_4.pickle',X_valid1_4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid1_4.pickle',y_valid1_4)

In [ ]:
# fold 5
random.seed(5)
random.shuffle(train_values1)

x_train1_5 = tf.concat(train_values1[0:27], axis = 0)
X_train1_5 = x_train1_5[:,:,:-1].numpy()
y_train1_5 = x_train1_5[:,0,-1].numpy()

x_valid1_5 = tf.concat(train_values1[27:31], axis = 0)
X_valid1_5 = x_valid1_5[:,:,:-1].numpy()
y_valid1_5 = x_valid1_5[:,0,-1].numpy()

# scale
X_train1_5, X_valid1_5, _ = x_scaler(X_train1_5, X_valid1_5)


print("X_train:",X_train1_5.shape,
      "X_valid:",X_valid1_5.shape,
      "y_train:",y_train1_5.shape,
      "y_valid:",y_valid1_5.shape)

X_train: (2298, 576, 51) X_valid: (340, 576, 51) y_train: (2298,) y_valid: (340,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train1_5.pickle',X_train1_5)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train1_5.pickle',y_train1_5)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid1_5.pickle',X_valid1_5)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid1_5.pickle',y_valid1_5)

# Method 5 - Reframe to 576 and hands sensor configuration (HSC)

In [ ]:
data = open_pickle('/content/drive/MyDrive/Sam/File_saved/P_dct.pickle')
markers = open_pickle('/content/drive/MyDrive/Sam/File_saved/markers_dct.pickle')

In [ ]:
data['P01_acc']

,Frame,Pelvis x,Pelvis y,Pelvis z,T8 x,T8 y,T8 z,Head x,Head y,Head z,...,Left Upper Leg x,Left Upper Leg y,Left Upper Leg z,Left Lower Leg x,Left Lower Leg y,Left Lower Leg z,Left Foot x,Left Foot y,Left Foot z,Label
0,0,-0.000099,0.000712,-0.001159,0.246312,0.497346,-0.011794,0.345373,0.292784,0.172301,...,0.197891,-0.037716,-0.172511,0.441520,0.708759,-0.073357,0.267160,0.507843,-0.020744,Do not use
1,1,0.085870,-0.087079,-0.057492,0.270516,0.329011,-0.041490,0.342595,0.234431,-0.069587,...,0.286065,-0.283458,-0.174133,0.460206,0.508014,-0.051261,0.277574,0.392253,-0.037118,Do not use
2,2,0.043551,0.023407,0.000055,0.144880,0.406876,-0.017420,0.333028,0.329907,0.038479,...,0.222336,-0.221622,-0.120159,0.261654,0.588018,0.066416,0.195962,0.589012,0.046372,Do not use
3,3,-0.052281,0.032851,0.023840,0.005390,0.444358,0.020782,0.121774,0.415970,-0.086135,...,0.159082,-0.272581,-0.061035,0.051586,0.487235,0.108227,-0.042877,0.572785,0.003310,Do not use
4,4,0.005050,0.062071,0.025009,0.033177,0.315881,-0.070002,0.261215,0.304412,-0.195614,...,0.200309,-0.383079,-0.046320,-0.065462,0.314675,0.132233,0.055484,0.435952,-0.003216,Do not use
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398051,398051,0.109546,-0.192590,-0.019474,-0.016441,0.767020,-0.752473,1.434921,-0.467081,-1.171233,...,2.588507,6.441144,4.806530,-3.295399,1.378654,5.273978,-1.511757,2.380366,2.058949,Do not use
398052,398052,0.225429,-0.056844,0.079336,0.204197,0.582222,-0.461302,1.589540,-0.450009,-0.790704,...,2.863125,6.368722,3.993892,-3.239406,0.794041,5.558134,-1.645143,2.114684,2.426376,Do not use
398053,398053,0.027821,-0.216023,-0.066449,0.153890,0.150679,-0.402773,1.425629,-0.744814,-0.667597,...,2.182594,4.981315,2.295814,-3.370394,0.431018,5.052170,-1.888646,1.568463,2.351394,Do not use
398054,398054,-0.662307,-0.298908,-0.416978,-0.398631,-0.325173,-0.665061,0.774213,-1.156998,-0.832347,...,0.371587,2.671983,0.513763,-4.072240,0.520759,3.967976,-2.509244,1.009905,2.074472,Do not use
398055,398055,-0.905923,-0.638321,-0.650060,-0.447897,-1.049062,-0.843251,0.575945,-1.781038,-0.920370,...,-1.260911,-0.335961,-0.837057,-4.095988,0.747124,2.856573,-2.732090,0.203242,1.885064,Do not use

In [ ]:
markers['P01_markers']

     Satrt of trial Marker Text  Trial length
0                 0  Do not use        1112.0
1              1112          OT         440.0
2              1552        post        2768.0
3              4320          OT         392.0
4              4712        post        2736.0
..              ...         ...           ...
164          316216          WS         400.0
165          316616        post        4400.0
166          321016        Rest        8640.0
167          329656  Do not use       68384.0
168          398040         end           NaN

[169 rows x 3 columns]

In [ ]:
# Selecting the sensor configuration
data_HSC = {}
for i in data:
  data_HSC[f'{i}_H'] = data[i].loc[:,('Frame','Right Hand x','Right Hand y','Right Hand z','Left Hand x','Left Hand y','Left Hand z','Label')]

In [ ]:
# Preprocess function for method 5 and storing into 'P_processed5' dictionary
P_processed5 = {}
for l,n in zip(markers, data_HSC):
  P_processed5[f'{n}_processed5'], data_classes5 = Preprocess(markers[l],data_HSC[n])

In [ ]:
data_classes5

array(['BH', 'OT', 'Other', 'Pass', 'Rest', 'SS', 'WS'], dtype=object)

In [ ]:
# Subject-wise shuffling
keys = list(P_processed5.keys())
random.seed(10)
random.shuffle(keys)

ShuffledP_processed5_1 = dict()
for key in keys:
    ShuffledP_processed5_1.update({key: P_processed5[key]})

In [ ]:
# fold 1
train_values5 = list(ShuffledP_processed5_1.values())[0:31]
x_train_all5 = tf.concat(train_values5[0:31], axis = 0)
X_train_all5 = x_train_all5[:,:,:-1].numpy()
y_train_all5 = x_train_all5[:,0,-1].numpy()
random.seed(6)
random.shuffle(train_values5)

x_train5_1 = tf.concat(train_values5[0:27], axis = 0)
X_train5_1 = x_train5_1[:,:,:-1].numpy()
y_train5_1 = x_train5_1[:,0,-1].numpy()

x_valid5_1 = tf.concat(train_values5[27:31], axis = 0)
X_valid5_1 = x_valid5_1[:,:,:-1].numpy()
y_valid5_1 = x_valid5_1[:,0,-1].numpy()

test_values5 = list(ShuffledP_processed5_1.values())[31:39]
x_test5 = tf.concat(test_values5, axis = 0)
X_test5 = x_test5[:,:,:-1].numpy()
y_test5 = x_test5[:,0,-1].numpy()


X_train5_1, X_valid5_1, _ = x_scaler(X_train5_1, X_valid5_1)


print("X_train:",X_train5_1.shape,
      "X_test:",X_test5.shape,
      "X_valid:",X_valid5_1.shape,
      "y_train:",y_train5_1.shape,
      "y_test:",y_test5.shape,
      "y_valid:",y_valid5_1.shape,
      "X_train:",X_train_all5.shape,
      "y_train:",y_train_all5.shape)

X_train: (2298, 576, 6) X_test: (681, 576, 6) X_valid: (340, 576, 6) y_train: (2298,) y_test: (681,) y_valid: (340,) X_train: (2638, 576, 6) y_train: (2638,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train5_1.pickle',X_train5_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid5_1.pickle',X_valid5_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_test5.pickle',y_test5)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train5_1.pickle',y_train5_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid5_1.pickle',y_valid5_1)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train_all5.pickle',y_train_all5)

In [ ]:
# ---- Global scaler for the FINAL model (fit on TRAIN_ALL only) ----
import numpy as np

def x_scaler(X_train, X_valid=None, X_test=None, mean=None, std=None, return_params=False, eps=1e-8):
    if mean is None or std is None:
        mean = X_train.mean(axis=(0, 1), keepdims=True)
        std  = X_train.std(axis=(0, 1), keepdims=True)
    std = np.where(std < eps, eps, std)

    X_train = (X_train - mean) / std
    X_valid = None if X_valid is None else (X_valid - mean) / std
    X_test  = None if X_test  is None else (X_test  - mean) / std

    if return_params:
        return X_train, X_valid, X_test, {"mean": mean, "std": std}
    return X_train, X_valid, X_test

# Fit on TRAIN_ALL; apply to TRAIN_ALL (for your final model) and to TEST
X_train_all5_sc, _, X_test5_sc, scale_global5 = x_scaler(
    X_train_all5, None, X_test5, return_params=True
)

# Save the scaled arrays (or at least the scale params)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train_all5_sc.pickle', X_train_all5_sc)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_test5_sc.pickle',     X_test5_sc)
save_pickle('/content/drive/MyDrive/Sam/File_saved/scale_global5.pickle',   scale_global5)

# Quick sanity check (optional)
def stats(X, name):
    mu = X.mean(axis=(0,1)); sd = X.std(axis=(0,1))
    print(f"{name}: mean[:5]={mu[:5]}, std[:5]={sd[:5]}")

stats(X_train_all5_sc, "TRAIN_ALL5_sc")
stats(X_test5_sc,     "TEST5_sc")
# stds should be ≈1 and means ≈0 per channel for both.

TRAIN_ALL5_sc: mean[:5]=[-2.1309717e-08  5.0227598e-08  3.3191029e-08  1.2846766e-07
  2.0452193e-08], std[:5]=[0.9998885  0.9999109  0.99991244 0.99991894 0.99991584]
TEST5_sc: mean[:5]=[-0.00329391 -0.00043482  0.00827742  0.00321556 -0.00141573], std[:5]=[0.9748667 1.0317595 0.9659537 0.9358885 0.9215886]

In [ ]:
# fold 2
random.seed(7)
random.shuffle(train_values5)

x_train5_2 = tf.concat(train_values5[0:27], axis = 0)
X_train5_2 = x_train5_2[:,:,:-1].numpy()
y_train5_2 = x_train5_2[:,0,-1].numpy()

x_valid5_2 = tf.concat(train_values5[27:31], axis = 0)
X_valid5_2 = x_valid5_2[:,:,:-1].numpy()
y_valid5_2 = x_valid5_2[:,0,-1].numpy()

X_train5_2, X_valid5_2, _ = x_scaler(X_train5_2, X_valid5_2)


print("X_train:",X_train5_2.shape,
      "X_valid:",X_valid5_2.shape,
      "y_train:",y_train5_2.shape,
      "y_valid:",y_valid5_2.shape)

X_train: (2298, 576, 6) X_valid: (340, 576, 6) y_train: (2298,) y_valid: (340,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train5_2.pickle',X_train5_2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train5_2.pickle',y_train5_2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid5_2.pickle',X_valid5_2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid5_2.pickle',y_valid5_2)

In [ ]:
# fold 3
random.seed(8)
random.shuffle(train_values5)

x_train5_3 = tf.concat(train_values5[0:27], axis = 0)
X_train5_3 = x_train5_3[:,:,:-1].numpy()
y_train5_3 = x_train5_3[:,0,-1].numpy()

x_valid5_3 = tf.concat(train_values5[27:31], axis = 0)
X_valid5_3 = x_valid5_3[:,:,:-1].numpy()
y_valid5_3 = x_valid5_3[:,0,-1].numpy()

X_train5_3, X_valid5_3, _ = x_scaler(X_train5_3, X_valid5_3)


print("X_train:",X_train5_3.shape,
      "X_valid:",X_valid5_3.shape,
      "y_train:",y_train5_3.shape,
      "y_valid:",y_valid5_3.shape)

X_train: (2298, 576, 6) X_valid: (340, 576, 6) y_train: (2298,) y_valid: (340,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train5_3.pickle',X_train5_3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train5_3.pickle',y_train5_3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid5_3.pickle',X_valid5_3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid5_3.pickle',y_valid5_3)

In [ ]:
# fold 4
random.seed(9)
random.shuffle(train_values5)

x_train5_4 = tf.concat(train_values5[0:27], axis = 0)
X_train5_4 = x_train5_4[:,:,:-1].numpy()
y_train5_4 = x_train5_4[:,0,-1].numpy()

x_valid5_4 = tf.concat(train_values5[27:31], axis = 0)
X_valid5_4 = x_valid5_4[:,:,:-1].numpy()
y_valid5_4 = x_valid5_4[:,0,-1].numpy()

X_train5_4, X_valid5_4, _ = x_scaler(X_train5_4, X_valid5_4)


print("X_train:",X_train5_4.shape,
      "X_valid:",X_valid5_4.shape,
      "y_train:",y_train5_4.shape,
      "y_valid:",y_valid5_4.shape)

X_train: (2297, 576, 6) X_valid: (341, 576, 6) y_train: (2297,) y_valid: (341,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train5_4.pickle',X_train5_4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train5_4.pickle',y_train5_4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid5_4.pickle',X_valid5_4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid5_4.pickle',y_valid5_4)

In [ ]:
# fold 5
random.seed(5)
random.shuffle(train_values5)

x_train5_5 = tf.concat(train_values5[0:27], axis = 0)
X_train5_5 = x_train5_5[:,:,:-1].numpy()
y_train5_5 = x_train5_5[:,0,-1].numpy()

x_valid5_5 = tf.concat(train_values5[27:31], axis = 0)
X_valid5_5 = x_valid5_5[:,:,:-1].numpy()
y_valid5_5 = x_valid5_5[:,0,-1].numpy()

X_train5_5, X_valid5_5, _ = x_scaler(X_train5_5, X_valid5_5)


print("X_train:",X_train5_5.shape,
      "X_valid:",X_valid5_5.shape,
      "y_train:",y_train5_5.shape,
      "y_valid:",y_valid5_5.shape)

X_train: (2298, 576, 6) X_valid: (340, 576, 6) y_train: (2298,) y_valid: (340,)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train5_5.pickle',X_train5_5)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train5_5.pickle',y_train5_5)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_valid5_5.pickle',X_valid5_5)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_valid5_5.pickle',y_valid5_5)

# Other methods

## Method 2 - Reframe to 576 frames and Biomechanics Sensor Configuration (BSC)

In [ ]:
data = open_pickle('/content/drive/MyDrive/Sam/File_saved/P_dct.pickle')
markers = open_pickle('/content/drive/MyDrive/Sam/File_saved/markers_dct.pickle')

In [ ]:
# Selecting the sensor configuration
data_BSC = {}
for i in data:
  data_BSC[f'{i}_bmech'] = data[i].loc[:,('Frame','Right Hand x','Right Hand y','Right Hand z','Left Hand x','Left Hand y','Left Hand z',
                                                     'Right Foot x','Right Foot y','Right Foot z','Left Foot x','Left Foot y','Left Foot z',
                                                     'Pelvis x','Pelvis y','Pelvis z','Label')]

KeyboardInterrupt:

In [ ]:
# Preprocess function for method 2 and storing into 'P_processed2' dictionary
P_processed2 = {}
for l,n in zip(markers, data_BSC):
  P_processed2[f'{n}_processed2'], data_classes2 = Preprocess(markers[l],data_BSC[n])

In [ ]:
data_classes2

In [ ]:
# Subject-wise shuffling
keys = list(P_processed2.keys())
random.seed(10)
random.shuffle(keys)

SuffledP_processed2 = dict()
for key in keys:
    SuffledP_processed2.update({key: P_processed2[key]})

In [ ]:
# Splitting data and labels in train/test
train_values2 = list(SuffledP_processed2.values())[0:31]
x_train2 = tf.concat(train_values2, axis = 0)
X_train2 = x_train2[:,:,:-1].numpy()
y_train2 = x_train2[:,0,-1].numpy()

test_values2 = list(SuffledP_processed2.values())[31:39]
x_test2 = tf.concat(test_values2, axis = 0)
X_test2 = x_test2[:,:,:-1].numpy()
y_test2 = x_test2[:,0,-1].numpy()

print("X_train:",X_train2.shape,
      "X_test:",X_test2.shape,
      "y_train:",y_train2.shape,
      "y_test:",y_test2.shape)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_test2.pickle',X_test2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train2.pickle',X_train2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_test2.pickle',y_test2)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train2.pickle',y_train2)

## Method 3 - Resampling and BSC

In [ ]:
data = open_pickle('/content/drive/MyDrive/Sam/File_saved/P_dct.pickle')
markers = open_pickle('/content/drive/MyDrive/Sam/File_saved/markers_dct.pickle')

In [ ]:
# Selecting the sensor configuration
data_biomech_config = {}
for i in data:
  data_biomech_config[f'{i}_bmech'] = data[i].loc[:,('Frame','Right Hand x','Right Hand y','Right Hand z','Left Hand x','Left Hand y','Left Hand z',
                                                     'Right Foot x','Right Foot y','Right Foot z','Left Foot x','Left Foot y','Left Foot z',
                                                     'Pelvis x','Pelvis y','Pelvis z','Label')]

In [ ]:
# Empty dictionary for place holding
data_resample = {'P01_resample_bmech':{},'P02_resample_bmech':{},'P03_resample_bmech':{},'P04_resample_bmech':{},'P05_resample_bmech':{},'P07_resample_bmech':{},'P08_resample_bmech':{},
                 'P09_resample_bmech':{},'P10_resample_bmech':{},'P11_resample_bmech':{},'P12_resample_bmech':{},'P13_resample_bmech':{},'P14_resample_bmech':{},'P15_resample_bmech':{},
                 'P16_resample_bmech':{},'P17_resample_bmech':{},'P18_resample_bmech':{},'P19_resample_bmech':{},'P20_resample_bmech':{},'P21_resample_bmech':{},'P22_resample_bmech':{},
                 'P23_resample_bmech':{},'P24_resample_bmech':{},'P25_resample_bmech':{},'P26_resample_bmech':{},'P27_resample_bmech':{},'P28_resample_bmech':{},'P29_resample_bmech':{},
                 'P32_resample_bmech':{},'P33_resample_bmech':{},'P34_resample_bmech':{},'P35_resample_bmech':{},'P36_resample_bmech':{},'P37_resample_bmech':{},'P39_resample_bmech':{},
                 'P40_resample_bmech':{},'P41_resample_bmech':{},'P42_resample_bmech':{},'P43_resample_bmech':{}}

In [ ]:
# Runs some preprocessing steps and storing it into a new dictionary 'data_biomech'
data_biomech = {}
for j1,j2 in zip(markers, data_biomech_config):

  P_data = regroup_other(markers[j1], data_biomech_config[j2]) # regroups the 'SH', 'Pre', 'post' trials to the label 'Other'
  P_other = P_data[(P_data['Label'] == 'Other')] # creates a variable containing all the data labeled 'Other'
  P_other_all = other_class(P_other,400) # from the variable above, creates 15 trials of length 400
  P_data = P_data.drop(P_data[(P_data['Label'] == 'Do not use')].index) # removing all the data labeled as 'Do not use' (junk)
  P_data = P_data.drop(P_data[(P_data['Label'] == 'Other')].index) # removing all the data labeled as 'Other' from the original dataset
  P_data = pd.concat([P_data, P_other_all], ignore_index = True) # adding the 15 'Other' trials of length 400 to the original dataset
  data_biomech[f'{j2}'], data_classes3 = stand_labelencoder(P_data)

In [ ]:
data_classes3

In [ ]:
# This runs 3 different functions from the same 3 dictionaries
data_other = {}
data_rest = {}
for m1,m2,m3 in zip(markers, data_resample, data_biomech):
  # Resampling the shooting trials to 400 frames and store them into the 'data_resample' dictionary
  resampling_data(m1,m2,m3, 400)
  # Creates a tensor of 'Other' from the 'data_biomech' dictionary and swap the axes to the required shape
  other = data_biomech[m3][-6000:,:]
  data_other[f'{m3}_other'] = create_tensor(other, 400)
  # Creates a tensor of 'Rest' from the data_biomech' dictionary and swap the axes to the required shape
  rest = data_biomech[m3][(data_biomech[m3][:,-1] == 4)]
  rest = rest[0:6000,:]
  data_rest[f'{m3}_rest'] = create_tensor(rest,400)

In [ ]:
# Converting the shots data from the 'data_resample' dictionary into tensor and store it into 'data_tensor' dictionary
data_tensor = {}
for i in data_resample:
  keys = data_resample[i].keys()
  t = np.array([data_resample[i][j] for j in keys])
  data_tensor[f'{i}_tensor'] = tf.convert_to_tensor(t, dtype = tf.float32)

In [ ]:
# Regrouping the shots, 'Other' and 'Rest' trials together in the 'data_tensor' dictionary
for n1,n2,n3 in zip(data_tensor, data_other, data_rest):
  data_tensor[n1] = tf.concat([data_tensor[n1],data_other[n2]], 0)
  data_tensor[n1] = tf.concat([data_tensor[n1],data_rest[n3]], 0)

In [ ]:
# Subject-wise shuffling
keys = list(data_tensor.keys())
random.seed(10)
random.shuffle(keys)

Shuffled_data_tensor = dict()
for key in keys:
    Shuffled_data_tensor.update({key: data_tensor[key]})

In [ ]:
# Splitting data and labels in train/test
train_values3 = list(Shuffled_data_tensor.values())[0:31]
x_train3 = tf.concat(train_values3, axis = 0)
X_train3 = x_train3[:,:,:-1].numpy()
y_train3 = x_train3[:,0,-1].numpy()

test_values3 = list(Shuffled_data_tensor.values())[31:39]
x_test3 = tf.concat(test_values3, axis = 0)
X_test3 = x_test3[:,:,:-1].numpy()
y_test3 = x_test3[:,0,-1].numpy()

print("X_train:",X_train3.shape,
      "X_test:",X_test3.shape,
      "y_train:",y_train3.shape,
      "y_test:",y_test3.shape)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_test3.pickle',X_test3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train3.pickle',X_train3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_test3.pickle',y_test3)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train3.pickle',y_train3)

## Method 4 - Reframe to 576 and hands/feet sensor configuration (HFSC)

In [ ]:
data = open_pickle('/content/drive/MyDrive/Sam/File_saved/P_dct.pickle')
markers = open_pickle('/content/drive/MyDrive/Sam/File_saved/markers_dct.pickle')

In [ ]:
# Selecting the sensor configuration
data_HFSC = {}
for i in data:
  data_HFSC[f'{i}_HF'] = data[i].loc[:,('Frame','Right Hand x','Right Hand y','Right Hand z','Left Hand x','Left Hand y','Left Hand z',
                                        'Right Foot x','Right Foot y','Right Foot z','Left Foot x','Left Foot y','Left Foot z','Label')]

In [ ]:
# Preprocess function for method 4 and storing into 'P_processed4' dictionary
P_processed4 = {}
for l,n in zip(markers, data_HFSC):
  P_processed4[f'{n}_processed4'], data_classes4 = Preprocess(markers[l],data_HFSC[n])

In [ ]:
data_classes4

In [ ]:
# Subject-wise shuffling
keys = list(P_processed4.keys())
random.seed(10)
random.shuffle(keys)

SuffledP_processed4 = dict()
for key in keys:
    SuffledP_processed4.update({key: P_processed4[key]})

In [ ]:
# Splitting data and labels in train/test
train_values4 = list(SuffledP_processed4.values())[0:31]
x_train4 = tf.concat(train_values4, axis = 0)
X_train4 = x_train4[:,:,:-1].numpy()
y_train4 = x_train4[:,0,-1].numpy()

test_values4 = list(SuffledP_processed4.values())[31:39]
x_test4 = tf.concat(test_values4, axis = 0)
X_test4 = x_test4[:,:,:-1].numpy()
y_test4 = x_test4[:,0,-1].numpy()

print("X_train:",X_train4.shape,
      "X_test:",X_test4.shape,
      "y_train:",y_train4.shape,
      "y_test:",y_test4.shape)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_test4.pickle',X_test4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train4.pickle',X_train4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_test4.pickle',y_test4)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train4.pickle',y_train4)

## Method 6 - Reframe to 576 and hands/feet/torso sensor configuration (HFTSC)

In [ ]:
data = open_pickle('/content/drive/MyDrive/Sam/File_saved/P_dct.pickle')
markers = open_pickle('/content/drive/MyDrive/Sam/File_saved/markers_dct.pickle')

In [ ]:
# Selecting the sensor configuration
data_HFTSC = {}
for i in data:
  data_HFTSC[f'{i}_HFT'] = data[i].loc[:,('Frame','T8 x','T8 y','T8 z','Right Hand x','Right Hand y','Right Hand z','Left Hand x','Left Hand y','Left Hand z',
                                         'Right Foot x','Right Foot y','Right Foot z','Left Foot x','Left Foot y','Left Foot z','Label')]

In [ ]:
# Preprocess function for method 4 and storing into 'P_processed4' dictionary
P_processed6 = {}
for l,n in zip(markers, data_HFTSC):
  P_processed6[f'{n}_processed6'], data_classes6 = Preprocess(markers[l],data_HFTSC[n])

In [ ]:
data_classes6

In [ ]:
# Subject-wise shuffling
keys = list(P_processed6.keys())
random.seed(10)
random.shuffle(keys)

SuffledP_processed6 = dict()
for key in keys:
    SuffledP_processed6.update({key: P_processed6[key]})

In [ ]:
# Splitting data and labels in train/test
train_values6 = list(SuffledP_processed6.values())[0:31]
x_train6 = tf.concat(train_values6, axis = 0)
X_train6 = x_train6[:,:,:-1].numpy()
y_train6 = x_train6[:,0,-1].numpy()

test_values6 = list(SuffledP_processed6.values())[31:39]
x_test6 = tf.concat(test_values6, axis = 0)
X_test6 = x_test6[:,:,:-1].numpy()
y_test6 = x_test6[:,0,-1].numpy()

print("X_train:",X_train6.shape,
      "X_test:",X_test6.shape,
      "y_train:",y_train6.shape,
      "y_test:",y_test6.shape)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_test6.pickle',X_test6)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train6.pickle',X_train6)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_test6.pickle',y_test6)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train6.pickle',y_train6)

## Method 7 - Reframe to 576 and hands/Torso sensor configuration (HTSC)

In [ ]:
data = open_pickle('/content/drive/MyDrive/Sam/File_saved/P_dct.pickle')
markers = open_pickle('/content/drive/MyDrive/Sam/File_saved/markers_dct.pickle')

In [ ]:
# Selecting the sensor configuration
data_HTSC = {}
for i in data:
  data_HTSC[f'{i}_HT'] = data[i].loc[:,('Frame','T8 x','T8 y','T8 z','Right Hand x','Right Hand y','Right Hand z','Left Hand x','Left Hand y','Left Hand z',
                                        'Label')]

In [ ]:
# Preprocess function for method 4 and storing into 'P_processed4' dictionary
P_processed7 = {}
for l,n in zip(markers, data_HTSC):
  P_processed7[f'{n}_processed7'], data_classes7 = Preprocess(markers[l],data_HTSC[n])

In [ ]:
data_classes7

In [ ]:
# Subject-wise shuffling
keys = list(P_processed7.keys())
random.seed(10)
random.shuffle(keys)

SuffledP_processed7 = dict()
for key in keys:
    SuffledP_processed7.update({key: P_processed7[key]})

In [ ]:
# Splitting data and labels in train/test
train_values7 = list(SuffledP_processed7.values())[0:31]
x_train7 = tf.concat(train_values7, axis = 0)
X_train7 = x_train7[:,:,:-1].numpy()
y_train7 = x_train7[:,0,-1].numpy()

test_values7 = list(SuffledP_processed7.values())[31:39]
x_test7 = tf.concat(test_values7, axis = 0)
X_test7 = x_test7[:,:,:-1].numpy()
y_test7 = x_test7[:,0,-1].numpy()

print("X_train:",X_train7.shape,
      "X_test:",X_test7.shape,
      "y_train:",y_train7.shape,
      "y_test:",y_test7.shape)

In [ ]:
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_test7.pickle',X_test7)
save_pickle('/content/drive/MyDrive/Sam/File_saved/X_train7.pickle',X_train7)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_test7.pickle',y_test7)
save_pickle('/content/drive/MyDrive/Sam/File_saved/y_train7.pickle',y_train7)